accounts/urls.py
from django.urls import path
from accounts.views import signup

app_name = 'accounts'
urlpatterns = [
    path('signup/', signup, name='signup'),
]

jionyeshe/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'jionyeshe'
urlpatterns = [

    path('', views.index, name='index'),
    path('profile/', views.profile, name='profile'),
    path('category/<int:pk>/', views.category, name = 'category'),
    path('project/', views.project, name='project'),
    path('project/<int:pk>/', views.ProjectDetail.as_view(), name='detail'),
    path('review/', views.review, name='review'),
    
   
]

portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from . import settings

from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('jionyeshe.urls')),
]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models

# Create your models here.

jionyeshe/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth import get_user_model
from django.db.models.signals import post_save
from django.dispatch import receiver


# Create your models here.
User = get_user_model()
class Category(models.Model):
    name = models.CharField(max_length=100)

    class Meta:
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.name


class Profile(models.Model):
    user = models.OneToOneField(User, null=True, on_delete=models.CASCADE)
    bio = models.TextField(blank=True)
    profession = models.CharField(max_length=100)
    age = models.CharField(max_length=4)
    gender = models.CharField(max_length=10)
    phone = models.CharField(max_length=255, blank=True,
                             null=True)
    website = models.URLField(
        max_length=128,
        db_index=True,
        unique=True,
        blank=True)
    skills = models.CharField(max_length=200)


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)


@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()


class Project(models.Model):
    added_by = models.ForeignKey(
        User, on_delete=models.CASCADE, null=True, related_name="projects")
    category = models.ForeignKey(
        Category, on_delete=models.CASCADE, null=True, related_name='categories')
    title = models.CharField(max_length=100)
    description = models.TextField()
    created_on = models.DateField()
    duration = models.CharField(max_length=100)
    client_website = models.CharField(max_length=100)
    client_name = models.CharField(max_length=100)
    client_email = models.CharField(max_length=100)
    project_url = models.CharField(max_length=100)

    class Meta:
        ordering = ['-created_on']

    def __str__(self):
        return self.title
        


class Screenshot(models.Model):
    project = models.ForeignKey(
        Project, on_delete=models.CASCADE, related_name='images')
    photos = models.ImageField(null=True, upload_to='screenshots')

    def __str__(self):
        return '%s - %s ' % (self.project, self.photos)


class Review(models.Model):
    project = models.ForeignKey(
        Project, on_delete=models.CASCADE, null=True, related_name="reviews")
    client = models.CharField(max_length=100)
    review_description = models.TextField()
    added_on = models.DateTimeField(default=timezone.now)

    class Meta:
        ordering = ['-added_on']

    def __str__(self):
        return self.review_description

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class RegisterForm(UserCreationForm):
    first_name = forms.CharField()
    last_name = forms.CharField()
    email = forms.EmailField()
    phone_number = forms.CharField()
    username = forms.CharField()

    class Meta:
        model = User
        fields = ["first_name", "last_name", "email", "phone_number",
                  "username", "password1", "password2", ]

accounts/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login
from django.urls import reverse_lazy
from django.views import generic
from accounts.forms import RegisterForm


# class SignupView(generic.CreateView):
#     form_class = UserCreationForm
#     success_url = reverse_lazy('login')
#     template_name = 'signup.html'


def signup(request):
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
           user = form.save()
           login(request, user)
           return redirect('login')
    else:
        form = RegisterForm()
    return render(request, 'jionyeshe/signup.html', {'form': form})

jionyeshe/views.py
from django.shortcuts import render, get_object_or_404,redirect
from .models import Project, Category
from django.views.generic import DetailView
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
# Create your views here.


def index(request):
    return render(request, 'jionyeshe/index.html', {})


def profile(request):
    
    context = {'cat_lists': Category.objects.all()}

    return render(request, 'jionyeshe/profile.html', context)


def category(request, **kwargs):
    context = {'category_projects': Project.objects.filter(
        category_id=kwargs.get('pk')), 'cat_lists': Category.objects.all()}

    return render(request, 'jionyeshe/category.html', context)


def project(request):
    context = {'projects_lists': Project.objects.all().order_by('-created_on'), 'cat_lists': Category.objects.all()}

    return render(request, 'jionyeshe/project.html', context)


class ProjectDetail(DetailView):
    model = Project
    template_name = 'jionyeshe/project-detail.html'


def review(request):
    return render(request, 'jionyeshe/review.html', {})

jionyeshe/templates/jionyeshe/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <title>{% block title %}JASIM-Home{% endblock %}</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <meta name="description" content="" />
  <meta name="author" content="" />

  <!-- css -->
  <link href="https://fonts.googleapis.com/css?family=Noto+Serif:400,400italic,700|Open+Sans:300,400,600,700" rel="stylesheet">
  <link href="{% static 'jionyeshe/css/bootstrap.css' %}" rel="stylesheet" />
  <link href="{% static 'jionyeshe/css/bootstrap-responsive.css' %}" rel="stylesheet" />
  <link href="{% static 'jionyeshe/css/fancybox/jquery.fancybox.css' %}" rel="stylesheet">
  <link href="{% static 'jionyeshe/css/jcarousel.css' %}" rel="stylesheet" />
  <link href="{% static 'jionyeshe/css/flexslider.css' %}" rel="stylesheet" />
  <link href="{% static 'jionyeshe/css/style.css' %}" rel="stylesheet" />
  <!-- Theme skin -->
  <link href="{% static 'jionyeshe/skins/default.css' %}" rel="stylesheet" />
  <!-- Fav and touch icons -->
  <link rel="apple-touch-icon-precomposed" sizes="144x144" href="{% static 'jionyeshe/ico/apple-touch-icon-144-precomposed.png' %}" />
  <link rel="apple-touch-icon-precomposed" sizes="114x114" href="{% static 'jionyeshe/ico/apple-touch-icon-114-precomposed.png' %}" />
  <link rel="apple-touch-icon-precomposed" sizes="72x72" href="{% static 'jionyeshe/ico/apple-touch-icon-72-precomposed.png' %}" />
  <link rel="apple-touch-icon-precomposed" href="{% static 'jionyeshe/ico/apple-touch-icon-57-precomposed.png' %}" />
  <link rel="shortcut icon" href="{% static 'jionyeshe/ico/favicon.png' %}" />
   <!-- github calendar css -->
    <link
      rel="stylesheet"
      href="{% static 'jionyeshe/plugins/github-calendar/dist/github-calendar.css' %}"
    />
    <!-- github activity css -->
    <link
      rel="stylesheet"
      href="//cdnjs.cloudflare.com/ajax/libs/octicons/2.0.2/octicons.min.css"
    />
    <link
      rel="stylesheet"
      href="{% static 'jionyeshe/plugins/github-activity/github-activity-0.1.5.min.css' %}"
    />
  
</head>

<body>
  <div id="wrapper">
    <!-- toggle top area -->
    <div class="hidden-top">
      <div class="hidden-top-inner container">
        <div class="row">
          <div class="span12">
          </div>
        </div>
      </div>
    </div>
    <!-- end toggle top area -->
    <!-- start header -->
    <header>
      <div class="container ">
        <!-- hidden top area toggle link -->
        <!-- end toggle link -->
        <div class="row nomargin">
          <div class="span12">
            <div class="headnav">
              <!-- <form class="form-horizontal">
                <input type="text" name="search" placeholder="Search">
                <input type="submit" name="submit" value="Search" class="btn btn-danger">
              </form>
              <ul>
                <li><a href="#mySignup" data-toggle="modal"><i class="icon-user"></i> Sign up</a></li>
                <li><a href="#mySignin" data-toggle="modal">Sign in</a></li>
              </ul> -->
            </div>
          </div>
        </div>
        <div class="row">
          <div class="span4">
            <div class="logo">
              <a href="{% url 'jionyeshe:index' %}"><img src="{% static 'jionyeshe/img/logo.png' %}" alt="" class="logo" /></a>
              <h1>Show off your skills</h1>
            </div>
          </div>
          <div class="span8">
            <div class="navbar navbar-static-top">
              <div class="navigation">
                <nav>
                  <ul class="nav topnav">
                    <li class="active">
                      <a href="{% url 'jionyeshe:index' %}">Home</a>
                    </li>
                    <li>
                      <a href="#">Create your portfolio</a>
                    </li>
                    <li class="dropdown">
                      <a href="#">Portfolios <i class="icon-angle-down"></i></a>
                      <ul class="dropdown-menu">
                        <li><a href="{% url 'jionyeshe:project' %}">Featured portfolios</a></li>
                        <li><a href="#">Premium portfolios</a></li>
                      </ul>
                    </li>
                    <li>
                      <a href="#">About Us</a>
                    </li>
                    <li>
                      <a href="#">Contact</a>
                    </li>
                    {% if user.is_authenticated%}
                    <li>
                      <a href="{% url 'logout' %}">Log out </a>
                    </li>
                    {% else %}
                     <li>
                      <a href="{% url 'login' %}">Sign in </a>
                    </li>
                     <li>
                      <a href="{% url 'accounts:signup' %}">Sign up </a>
                    </li>
                    {% endif %}
                  </ul>
                </nav>
              </div>
              <!-- end navigation -->
            </div>
          </div>
        </div>
      </div>
    </header>
    <!-- end header -->
    {% block content %} {% endblock %}
    <section id="bottom">
      <div class="container">
        <div class="row">
          <div class="span12">
            <div class="aligncenter">
              <div id="twitter-wrapper">
                <div id="twitter">
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
    <footer>
      <div class="container">
        <div class="row">
          <div class="span3">
            <div class="widget">
              <h5 class="widgetheading">Browse pages</h5>
              <ul class="link-list">
                <li><a href="#">About our company</a></li>
                <li><a href="#">Our services</a></li>
                <li><a href="#">Meet our team</a></li>
                <li><a href="#">Explore our portfolio</a></li>
                <li><a href="#">Get in touch with us</a></li>
              </ul>
            </div>
          </div>
          <div class="span3">
            <div class="widget">
              <h5 class="widgetheading">Important stuff</h5>
              <ul class="link-list">
                <li><a href="#">Press release</a></li>
                <li><a href="#">Terms and conditions</a></li>
                <li><a href="#">Privacy policy</a></li>
                <li><a href="#">Career center</a></li>
                <li><a href="#">Flattern forum</a></li>
              </ul>
            </div>
          </div>
          <div class="span3">
            <!-- <div class="widget">
              <h5 class="widgetheading">Flickr photostream</h5>
              <div class="flickr_badge">
                <script type="text/javascript" src="http://www.flickr.com/badge_code_v2.gne?count=8&amp;display=random&amp;size=s&amp;layout=x&amp;source=user&amp;user=34178660@N03"></script>
              </div>
              <div class="clear">
              </div>
            </div> -->
          </div>
          <div class="span3">
            <div class="widget">
              <h5 class="widgetheading">Get in touch with us</h5>
              <address>
								<strong>Flattern studio, Pte Ltd</strong><br>
								 Springville center X264, Park Ave S.01<br>
								 Semarang 16425 Indonesia
					 		</address>
              <p>
                <i class="icon-phone"></i> (123) 456-7890 - (123) 555-7891 <br>
                <i class="icon-envelope-alt"></i> email@domainname.com
              </p>
            </div>
          </div>
        </div>
      </div>
      <div id="sub-footer">
        <div class="container">
          <div class="row">
            <div class="span6">
              <div class="copyright">
                <p>
                  <span>Portfolio &copy;2020. All right reserved.</span>
                </p>
                <div class="credits">
                  Designed and Made by  <a href="https://jasim.com/" target="_blank">JASIM</a>
                </div>
              </div>
            </div>
            <div class="span6">
              <ul class="social-network">
                <li><a href="#" data-placement="bottom" title="Facebook"><i class="icon-facebook icon-square"></i></a></li>
                <li><a href="#" data-placement="bottom" title="Twitter"><i class="icon-twitter icon-square"></i></a></li>
                <li><a href="#" data-placement="bottom" title="Linkedin"><i class="icon-linkedin icon-square"></i></a></li>
                <li><a href="#" data-placement="bottom" title="Pinterest"><i class="icon-pinterest icon-square"></i></a></li>
                <li><a href="#" data-placement="bottom" title="Google plus"><i class="icon-google-plus icon-square"></i></a></li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </footer>
  </div>
  <a href="#" class="scrollup"><i class="icon-chevron-up icon-square icon-32 active"></i></a>
  <!-- javascript
    ================================================== -->
  <!-- Placed at the end of the document so the pages load faster -->
  <script src="{% static 'jionyeshe/js/jquery.js' %}"></script>
  <script src="{% static 'jionyeshe/js/jquery.easing.1.3.js' %}"></script>
  <script src="{% static 'jionyeshe/js/bootstrap.js' %}"></script>
  <script src="{% static 'jionyeshe/js/jcarousel/jquery.jcarousel.min.js' %}"></script>
  <script src="{% static 'jionyeshe/js/jquery.fancybox.pack.js' %}"></script>
  <script src="{% static 'jionyeshe/js/jquery.fancybox-media.js' %}"></script>
  <script src="{% static 'jionyeshe/js/google-code-prettify/prettify.js' %}"></script>
  <script src="{% static 'jionyeshe/js/portfolio/jquery.quicksand.js' %}"></script>
  <script src="{% static 'jionyeshe/js/portfolio/setting.js' %}"></script>
  <script src="{% static 'jionyeshe/js/jquery.flexslider.js' %}"></script>
  <script src="{% static 'jionyeshe/js/jquery.nivo.slider.js' %}"></script>
  <script src="{% static 'jionyeshe/js/modernizr.custom.js' %}"></script>
  <script src="{% static 'jionyeshe/js/jquery.ba-cond.min.js' %}"></script>
  <script src="{% static 'jionyeshe/js/jquery.slitslider.js' %}"></script>
  <script src="{% static 'jionyeshe/js/animate.js' %}"></script>

  <!-- Template Custom JavaScript File -->
  <script src="{% static 'jionyeshe/js/custom.js' %}"></script>
  <!-- github calendar plugin -->
    <script
      type="text/javascript"
      src="{% static 'jionyeshe/plugins/github-calendar/dist/github-calendar.min.js' %}"
    ></script>
    <!-- github activity plugin -->
    <script
      type="text/javascript"
      src="//cdnjs.cloudflare.com/ajax/libs/mustache.js/0.7.2/mustache.min.js"
    ></script>
    <script
      type="text/javascript"
      src="{% static 'jionyeshe/plugins/github-activity/github-activity-0.1.5.min.js' %}"
    ></script>

</body>
</html>

jionyeshe/templates/jionyeshe/category.html
{% extends 'jionyeshe/base.html' %}
{% load static %}
{% block title %} Jionyeshe-Categories {% endblock %}
{% block content %}

<!-- end header -->
<section id="inner-headline">
    <div class="container">
      <div class="row">
        <div class="span4">
          <div class="inner-heading">
            <h2><b>
              {% if user.is_authenticated %}{{user.username}}</b></h2>
              {% else %}
              <p>You are not logged in</p>
              <a href="{% url 'login' %}">login</a>
              {% endif %}
            <p>Software Developer<b></b></p>
          </div>
        </div>
        <div class="span8">
          <ul class="breadcrumb">
            <li><a href="#"><i class="icon-home"></i></a><i class="icon-angle-right"></i></li>
            <li><a href="{% url 'jionyeshe:project' %}">Projects</a><i class="icon-angle-right"></i></li>
            <li class="active">Web Design</li>
          </ul>
        </div>
      </div>
    </div>
  </section>
  <section id="content">
    <div class="container">
      <div class="row">
        <div class="span8">
          <article>
            <h4><b>Web design Projects</b></h4>
            <p>
              Web based projects are projects/application which are deployed on world wide web (Internet) and these type of projects can be accessed by any device, any location, any configuration with just a url like <a href="www.google.com" target="_blank">Google</a>.This are projects developed using HTML5, CSS3, Javascript.
            </p>

            <br>
            <!-- divider -->
            <div class="row">
              <div class="span7">
                <div class="solidline">
                </div>
              </div>
            </div>
            <!-- end divider -->
            <h4><b>Projects</b></h4>
              <!-- <h4>Our expertise</h4> -->
              {% if category_projects%}
              {% for project in category_projects %}
              <div class="card-body" style="background-color: aliceblue; padding: 10px;border-radius: 10px;">
                <h5  class="card-title">{{ project.title }}</a></h5>
                <p class=" text-muted">{{project.client_name}}</p>
                <p class="card-text ">{{project.description|slice:":200"}}</p>
                <hr>
                <a href="{% url 'jionyeshe:detail' project.id %}" class="btn btn-primary">Read More</a>
                
            </div>
            <br>
            {% endfor %}
            {% else %}
            <h4>There are no projects for this category</h4>
            {% endif %}
                      

            
            <!-- divider -->
            <div class="row">
              <div class="span7">
                <br>
                <br>
                <div class="solidline">
                </div>
              </div>
            </div>
            <!-- end divider -->

            <div class="row">
              <div class="span8">
                <h4><strong>Clients</strong></h4>
                <ul id="mycarousel" class="jcarousel-skin-tango recent-jcarousel clients">
                  <li>
                    <a href="#">
              <img src="{% static 'jionyeshe/img/dummies/clients/client1.png' %}" class="client-logo" alt="" />
              </a>
                  </li>
                  <li>
                    <a href="#">
              <img src="{% static 'jionyeshe/img/dummies/clients/client2.png' %}" class="client-logo" alt="" />
              </a>
                  </li>
                  <li>
                    <a href="#">
              <img src="{% static 'jionyeshe/img/dummies/clients/client3.png' %}" class="client-logo" alt="" />
              </a>
                  </li>
                  <li>
                    <a href="#">
              <img src="{% static 'jionyeshe/img/dummies/clients/client4.png' %}" class="client-logo" alt="" />
              </a>
                  </li>
                  <li>
                    <a href="#">
              <img src="{% static 'jionyeshe/img/dummies/clients/client5.png' %}" class="client-logo" alt="" />
              </a>
                  </li>
                  <li>
                    <a href="#">
              <img src="{% static 'jionyeshe/img/dummies/clients/client6.png' %}" class="client-logo" alt="" />
              </a>
                  </li>
                  <li>
                    <a href="#">
              <img src="{% static 'jionyeshe/img/dummies/clients/client1.png' %}" class="client-logo" alt="" />
              </a>
                  </li>
                  <li>
                    <a href="#">
              <img src="{% static 'jionyeshe/img/dummies/clients/client2.png' %}" class="client-logo" alt="" />
              </a>
                  </li>
                  <li>
                    <a href="#">
              <img src="{% static 'jionyeshe/img/dummies/clients/client3.png' %}" class="client-logo" alt="" />
              </a>
                  </li>
                  <li>
                    <a href="#">
              <img src="{% static 'jionyeshe/img/dummies/clients/client4.png' %}" class="client-logo" alt="" />
              </a>
                  </li>
                  <li>
                    <a href="#">
              <img src="{% static 'jionyeshe/img/dummies/clients/client5.png' %}" class="client-logo" alt="" />
              </a>
                  </li>
                  <li>
                    <a href="#">
              <img src="{% static 'jionyeshe/img/dummies/clients/client6.png' %}" class="client-logo" alt="" />
              </a>
                  </li>
                </ul>
              </div>
            </div>

    
            
            <div class="solidline">

          </article>
        </div>
        <div class="span4">
          <aside class="right-sidebar">
            <div class="widget">
              <h5 class="widgetheading"><b>Project Categories</b></h5>
              {% for category in cat_lists %}
              <ul class="cat">
                <li><i class="icon-angle-right"></i><a href="{% url 'jionyeshe:category' category.id %}">{{category.name}}</a><span></span></li>
              </ul>
              {% endfor %}
              
            </div>
            <div class="widget">
              <h5 class="widgetheading"><b>All Reviews</b></h5>
              <div class="media">
              <a href="#" class="thumbnail pull-left"><img src="{% static 'jionyeshe/img/avatar.png' %}" alt="" /></a>
              <div class="media-body">
                <div class="media-content">
                  <h6><span>April 20, 2020</span> | Karen medisson</h6>
                  <p>
                    Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin commodo. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.
                  </p>
                  <!-- <a href="#" class="align-right">Reply comment</a> -->
                </div>
              </div>
            </div>
            <div class="media">
              <a href="#" class="thumbnail pull-left"><img src="{% static 'jionyeshe/img/avatar.png' %}" alt="" /></a>
              <div class="media-body">
                <div class="media-content">
                  <h6><span>March 20, 2020</span> |  Karen medisson</h6>
                  <p>
                    Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin commodo. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.
                  </p>
                  <!-- <a href="#" class="align-right">Reply comment</a> -->
                </div>
              </div>
            </div>
            </div>
          </aside>
        </div>
      </div>
    </div>
  </section>

{% endblock %}

jionyeshe/templates/jionyeshe/password_reset_email.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Forgot Your Password? {% endblock %}
{% block content %}
{% autoescape off %}
To initiate the password reset process for your {{ user.get_username }} TestSite Account,
click the link below:

{{ protocol }}://{{ domain }}{% url 'password_reset_confirm' uidb64=uid token=token %}

If clicking the link above doesn't work, please copy and paste the URL in a new browser
window instead.

Sincerely,
The TestSite Team
{% endautoescape %}
{% endblock %}

jionyeshe/templates/jionyeshe/project-detail.html
{% extends 'jionyeshe/base.html' %}
{% load static %}
{% block title %} Jionyeshe-Project details {% endblock %}
{% block content %}
    <section id="inner-headline">
      <div class="container">
        <div class="row">
          <div class="span4">
            <div class="inner-heading">
              <ul class="breadcrumb">
                <li><h3><a href="#">{{project.category}}</a><i class="icon-angle-right"></i></h3></li>
                <li class="active"><h6 style="color:#ffffff;">{{project.title}}</h6></li>
              </ul>
              <!-- <h2></h2> -->
            </div>
          </div>
          <div class="span8">
            <ul class="breadcrumb">
              <li><a href="#"><i class="icon-home"></i></a><i class="icon-angle-right"></i></li>
              <li><a href="{% url 'jionyeshe:project' %}">Projects</a><i class="icon-angle-right"></i></li>
              <li class="active">Project detail</li>
            </ul>
          </div>
        </div>
      </div>
    </section>
    <section id="content">
      <div class="container">
        <div class="row">
          <div class="span8">
            <article>
              <div class="top-wrapper">
                <div class="post-heading">
                  <!-- <h3><a href="#">This is an example of portfolio detail</a></h3> -->
                </div>
                <!-- start flexslider -->
                <div class="flexslider">
                  
                  <ul class="slides">
                    {% for image in project.images.all %}
                    <li>
                      <img src="{{image.photos.url}}" alt="" />
                    </li>
                    {% endfor %}
                  </ul>
                 
                </div>
                <!-- end flexslider -->
              </div>
              <h6>Description</h6>
              <p style="text-align: justify;">
                {{project.description}}
              </p>
            </article>
          </div>
          <div class="span4">
            <aside class="right-sidebar">
              <div class="widget">
                <h5 class="widgetheading">Project Info.</h5>
                <ul class="folio-detail">
                  <li><label style="margin-right:10px;">Project name :</label> {{project.title}}</li>
                  <li><label style="margin-right:40px;">Category :</label>{{project.category}}</li>
                  <li><label style="margin-right:60px;">Client :</label> {{project.client_name}}</li>
                  <li><label style="margin-right:20px;">Project date :</label> {{project.created_on}}</li>
                  <li><label style="margin-right:50px;">Duration:</label>{{project.duration}}</li>
                  <li><label style="margin-right:30px;">Project URL :</label><a href="{{project.project_url}}" target="_blank">{{project.title}}</a></li>
                </ul>
              </div>
              <div class="widget">
                <h5 class="widgetheading">Reviews</h5>
                <blockquote>
                  <p>The project was done perfectly.</p>
                    
                  </blockquote>
                  <p>—{{project.client_name}}</p>
              </div>
            </aside>
          </div>
        </div>
      </div>
    </section>
{% endblock %}

jionyeshe/templates/jionyeshe/review.html
{% extends 'jionyeshe/base.html' %}
{% load static %}
{% block content %}

<h2>Review</h2>

{% endblock %}

jionyeshe/templates/jionyeshe/signup.html
{% extends 'jionyeshe/base.html' %}
{% load static %}
{% block title %} Jionyeshe-Signup {% endblock %}
{% block content %}
<div class="container">
    <h2>Sign Up</h2>

    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <div class="control-group">
            <div class="controls">
                <button type="submit" class="btn">Sign up</button>
            </div>
            <p class="aligncenter margintop20">
                Already have an account? <a href="{% url 'login' %}" data-dismiss="modal" aria-hidden="true" data-toggle="modal">Sign in</a>
            </p>
        </div>
    </form>
</div>


{% endblock %}

jionyeshe/templates/review.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<h2>Review</h2>

{% endblock %}

jionyeshe/templates/signup.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Jionyeshe-Signup {% endblock %}
{% block content %}
<div class="container">
    <h2>Sign Up</h2>

    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <div class="control-group">
            <div class="controls">
                <button type="submit" class="btn">Sign up</button>
            </div>
            <p class="aligncenter margintop20">
                Already have an account? <a href="{% url 'login' %}" data-dismiss="modal" aria-hidden="true" data-toggle="modal">Sign in</a>
            </p>
        </div>
    </form>
</div>


{% endblock %}